kind: ReplicationController
apiVersion: v1
metadata:
  name: tornado-controller
  namespace: tornado
spec:
  replicas: 1
  selector:
    component: tornado
  template:
    metadata:
      labels:
        component: tornado
    spec:
      containers:
        - name: tornado
          image: sahandha/tornado
          imagePullPolicy: Never
          command: ["/bin/sh"]
          args: ["-c","cp -r /external/server /external/shared; python /external/shared/server/server.py"]
          ports:
            - containerPort: 27017
            - containerPort: 8888 
          volumeMounts:
            - mountPath: /external/shared
              name: nfsvol
          resources:
            requests:
              cpu: 100m
        - name: mongodb
          image: mongo
          imagePullPolicy: Never
          command: ["mongod"]
          ports:
            - containerPort: 27017
            - containerPort: 8888 
          #volumeMounts:
          #  - mountPath: /data/db
          #    name: mongodb-nfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: tornado-nfs
        #- name: mongodb-nfsvol
        #  persistentVolumeClaim:
        #    claimName: mongodb-nfs

