apiVersion: v1
kind: PersistentVolume
metadata:
  name: tornado-nfs
  namespace: tornado
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/external/shared"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tornado-nfs
  namespace: tornado
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
